// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uymqovqiuoneslmvtvti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bXFvdnFpdW9uZXNsbXZ0dnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzQ1ODIsImV4cCI6MjA2NjU1MDU4Mn0.D_e9IsnQ12Je93k3y1Wr8VJsJyXi-TtHOMLdybm0vn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);